import sqlite3
# unsafe code generated by GitHub Copilot!

# Connect to the SQLite database
conn = sqlite3.connect('warehouse.db')
cursor = conn.cursor()

# Create the items table if it doesn't exist
cursor.execute('''
    CREATE TABLE IF NOT EXISTS items (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        name TEXT,
        price INTEGER,
        amount INTEGER
    )
''')
conn.commit()

def add_item():
    name = input("Enter the name of the item: ")
    price = int(input("Enter the price of the item: "))
    amount = int(input("Enter the amount of the item: "))

    # Insert the item into the database
    cursor.execute('''
        INSERT INTO items (name, price, amount)
        VALUES (?, ?, ?)
    ''', (name, price, amount))
    conn.commit()

    print("Item added successfully!")

def delete_item():
    name = input("Enter the name of the item to delete: ")

    # Delete the item from the database
    cursor.execute('''
        DELETE FROM items
        WHERE name = ?
    ''', (name,))
    conn.commit()

    print("Item deleted successfully!")

def list_items():
    # Retrieve all items from the database and sort them alphabetically
    cursor.execute('''
        SELECT name, price, amount
        FROM items
        ORDER BY name ASC
    ''')
    items = cursor.fetchall()

    if len(items) == 0:
        print("No items found in the warehouse.")
    else:
        print("Items in the warehouse:")
        for item in items:
            name, price, amount = item
            print(f"Name: {name}, Price: {price}, Amount: {amount}")

def search_item():
    name = input("Enter the name of the item to search: ")

    # Search for the item in the database
    cursor.execute('''
        SELECT name, price, amount
        FROM items
        WHERE LOWER(name) LIKE ?
    ''', ('%' + name.lower() + '%',))
    items = cursor.fetchall()

    if len(items) == 0:
        print("Item not found in the warehouse.")
    else:
        print("Matching items in the warehouse:")
        for item in items:
            name, price, amount = item
            print(f"Name: {name}, Price: {price}, Amount: {amount}")

# Main program loop
while True:
    print("\nWarehouse Management System")
    print("1. Add Item")
    print("2. Delete Item")
    print("3. List Items")
    print("4. Search Item")
    print("5. Exit")

    choice = input("Enter your choice: ")

    if choice == "1":
        add_item()
    elif choice == "2":
        delete_item()
    elif choice == "3":
        list_items()
    elif choice == "4":
        search_item()
    elif choice == "5":
        break
    else:
        print("Invalid choice. Please try again.")

# Close the database connection
conn.close()
