import datetime

# Get the current date and time
current_datetime = datetime.datetime.now()
print("Current datetime:", current_datetime)
print("Current date:", current_datetime.date())
print("Current time:", current_datetime.time())
print("Current year:", current_datetime.year)
print("Current month:", current_datetime.month)
print("Current day:", current_datetime.day)
print("Current hour:", current_datetime.hour)
print("Current minute:", current_datetime.minute)
print("Current second:", current_datetime.second)
print("Current microsecond:", current_datetime.microsecond)
print("Current timezone:", current_datetime.tzinfo)
print("Current weekday:", current_datetime.weekday())
print("Current ISO week number:", current_datetime.isocalendar())
print("Current ISO calendar:", current_datetime.isocalendar())
print("Current week number:", current_datetime.strftime("%U"))
print("Current day of the year:", current_datetime.strftime("%j"))
print("Current day of the week:", current_datetime.strftime("%A"))
print("Current month name:", current_datetime.strftime("%B"))
print("Current AM/PM time:", current_datetime.strftime("%I:%M %p"))
print("Current 24-hour time:", current_datetime.strftime("%H:%M"))
print("Current date and time:", current_datetime.strftime("%Y-%m-%d %H:%M:%S"))
print("Current date and time with microseconds:", current_datetime.strftime("%Y-%m-%d %H:%M:%S.%f"))
print("Current date and time with timezone:", current_datetime.strftime("%Y-%m-%d %H:%M:%S %Z"))
print("Current date and time with timezone offset:", current_datetime.strftime("%Y-%m-%d %H:%M:%S %z"))
print("Current date and time with day of the week:", current_datetime.strftime("%A, %Y-%m-%d %H:%M:%S"))
print("Current date and time with month name:", current_datetime.strftime("%B %d, %Y %H:%M:%S"))
print("Current date and time with AM/PM:", current_datetime.strftime("%B %d, %Y %I:%M:%S %p"))

# compare dates
date1 = datetime.date(2021, 1, 1)
date2 = datetime.date(2021, 12, 31)
print("Date 1:", date1)
print("Date 2:", date2)
print("Date 1 is before Date 2:", date1 < date2)
print("Date 1 is after Date 2:", date1 > date2)
print("Date 1 is equal to Date 2:", date1 == date2)
timedelta = date2 - date1
print("Difference between Date 1 and Date 2:", timedelta)
date3 = date1+datetime.timedelta(days=10)
print("Date 1 + 10 days:", date3)

date1 = datetime.datetime.strptime('2021-01-01', '%Y-%m-%d')
date2 = datetime.datetime.strptime('2021-12-31', '%Y-%m-%d')
print("Date 1:", date1)
print("Date 2:", date2)
date3 = datetime.datetime.strptime('2021-12-30 12:10:59', '%Y-%m-%d %H:%M:%S')
print(date3)
